environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

cache:
  - 'C:\Users\%USERNAME%\.m2\repository'
  - '.gradle'
  - 'C:\Users\appveyor\.gradle'

install:
  # - gradle wrapper
  # - gradlew build
  # - gradlew.bat check
  # - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-19
  - ps: Start-FileDownload 'https://services.gradle.org/distributions/gradle-2.2-all.zip'
  - echo y | 7z e gradle-2.2-all.zip  C:\Program Files (x86)\
  - SET GRADLE_HOME=C:\Program Files (x86)\gradle-2.2\
  - echo %GRADLE_HOME%
  - SET PATH=%PATH%;%GRADLE_HOME%\bin
  - echo %PATH%
  - C:\Program Files (x86)\gradle-2.2\bin\gradle.bat -v

build: off