environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

cache:
  - 'C:\Users\%USERNAME%\.m2\repository'

install:
  - gradle wrapper
  - gradlew.bat check