environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

cache:
  - 'C:\Users\%USERNAME%\.m2\repository'
  - '.gradle'
  - 'C:\Users\appveyor\.gradle'

install:
  # - gradlew.bat check
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-19
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-20.0.0
  # - mkdir C:\Users\appveyor\.gradle
  # - ps: Start-FileDownload 'https://services.gradle.org/distributions/gradle-2.2-all.zip'
  # - echo y | 7z x gradle-2.2-all.zip  -o"C:\Users\appveyor\.gradle\"
  - SET GRADLE_HOME=C:\Users\appveyor\.gradle\gradle-2.2\
  - echo %GRADLE_HOME%
  - SET PATH=%PATH%;%GRADLE_HOME%\bin
  - ls %GRADLE_HOME%
  - gradle -v
  - gradle wrapper

build: off